services:
  backend:
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=$DATABASE_URL
    build:
      context: backend
      dockerfile: Dockerfile
    image: leoalmeida/backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
      target: development
    image: leoalmeida/frontend
    ports:
      - 8080:8080
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    networks:
      - react-express

networks:
  react-express: