services:
  backend:
    restart: unless-stopped
    environment:
      - DATABASE_URL=$DATABASE_URL
    build:
      context: backend
      dockerfile: Dockerfile
    image: leoalmeida/backend
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
      
