name: Docker

on:
  workflow_call:

jobs:
  backend:
    runs-on: node:lts-buster-slim
    steps:
    - uses: actions/checkout@v3
    - name: Set Docker Build
      uses: docker/setup-buildx-action@v3.10.0
    - name: Docker login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Docker push backend
      uses: docker/build-push-action@v6.15.0
      with:
        file: ./backend/Dockerfile
        context: backend
        push: true
        tags: leoalmeida/backend:${{github.run_number}}
